//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSkill()
        {
            this.AllocatedSeats = new HashSet<AllocatedSeat>();
        }
    
        public int UserSkillId { get; set; }
        public int UserId { get; set; }
        public int SkillId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllocatedSeat> AllocatedSeats { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual User User { get; set; }
    }
}
